/* PLayer's constants */
export const ADD_PLAYER = 'ADD_PLAYER';
export const EDIT_PLAYER = 'EDIT_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const TOGGLE_PLAYER_EDIT_MODE = 'TOGGLE_PLAYER_EDIT_MODE';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const ADD_PLAYER_NOTE = 'ADD_PLAYER_NOTE';
export const REMOVE_PLAYER_NOTE = 'REMOVE_PLAYER_NOTE';
export const SET_PLAYER_NOTE_SCORE = 'SET_PLAYER_NOTE_SCORE';
export const SET_PLAYER_NOTE_TRUMP = 'SET_PLAYER_NOTE_TRUMP';
export const SET_PLAYER_NOTE_FINE = 'SET_PLAYER_NOTE_FINE';
export const CALCULATE_PLAYER_SCORE = 'CALCULATE_PLAYER_SCORE';
export const PLAYER_CHECK = 'PLAYER_CHECK';

/* Game Options constants */
export const SET_WIN_SCORE = 'SET_WIN_SCORE';
export const TOGGLE_OPTIONS_WINDOW = 'TOGGLE_OPTIONS_WINDOW';

/*Game Notes constants */
export const ADD_GAME_NOTE = 'ADD_GAME_NOTE';
export const REMOVE_GAME_NOTE = 'REMOVE_GAME_NOTE';
export const SET_GAME_NOTE_STAKE = "SET_GAME_NOTE_STAKE";
export const SET_GAME_NOTE_REST_CARDS = 'SET_GAME_NOTE_REST_CARDS';
